"use strict";
const canvas=document.querySelector("#game"),ctx=canvas.getContext("2d"),nextCtx=document.querySelector("#next").getContext("2d");
const $=s=>document.querySelector(s), ui={score:$("#score"),best:$("#best"),chain:$("#chain"),warning:$("#warning")};
const LEVELS=[
 {n:"Spark",r:21,c:"#aefcff"},{n:"Ember",r:26,c:"#ffd85c"},{n:"Dew",r:36,c:"#6fffb4"},{n:"Nova",r:44,c:"#ff77be"},{n:"Halo",r:55,c:"#aa7cff"},{n:"Terra",r:68,c:"#48bfff"},{n:"Sol",r:81,c:"#ff9748"},{n:"Astra",r:96,c:"#f45f7d"},{n:"Giant",r:112,c:"#5bd6c5"},{n:"Quasar",r:128,c:"#c17cff"},{n:"Cosma",r:147,c:"#fff1a1"}
];
let W=360,H=600,dpr=1,bodies=[],particles=[],ripples=[],floaters=[],running=false,paused=false,gameOver=false,aimX=180,current=0,next=0,canDrop=true,score=0,best=+(localStorage.cosmoDropsBest||0),maxLevel=0,dropId=0,chain=0,chainTimer=0,dangerSince=0,last=0,audio=null,soundOn=localStorage.cosmoDropsSound!=="off",shake=0;
ui.best.textContent=best; $("#sound").classList.toggle("muted",!soundOn);
function resize(){const r=canvas.getBoundingClientRect();dpr=Math.min(devicePixelRatio||1,2);W=r.width;H=r.height;canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);aimX=Math.max(28,Math.min(W-28,aimX));}
addEventListener("resize",resize); new ResizeObserver(resize).observe(canvas);
function rndNext(){const p=Math.random();return p<.55?0:p<.84?1:p<.97?2:3}
function createBody(x,y,level,source=dropId){const L=LEVELS[level];const b={x,y,vx:0,vy:0,r:L.r,level,mass:L.r*L.r,merge:false,source,age:0,spin:Math.random()*6};bodies.push(b);maxLevel=Math.max(maxLevel,level);return b}
function reset(){bodies=[];particles=[];ripples=[];floaters=[];score=0;maxLevel=0;dropId=0;chain=0;dangerSince=0;gameOver=false;paused=false;canDrop=true;current=rndNext();next=rndNext();aimX=W/2;updateScore();drawNext();ui.warning.classList.remove("on");}
function start(){initAudio();reset();running=true;last=performance.now();$("#startOverlay").classList.remove("visible");$("#gameoverOverlay").classList.remove("visible");requestAnimationFrame(loop)}
function drop(){if(!running||paused||gameOver||!canDrop)return;initAudio();dropId++;chain=0;createBody(aimX,56,current,dropId);tone("drop",current);current=next;next=rndNext();drawNext();canDrop=false;setTimeout(()=>{if(running&&!gameOver)canDrop=true},430)}
function update(dt){const sub=2,step=dt/sub;for(let s=0;s<sub;s++){for(const b of bodies){b.age+=step;b.vy+=980*step;b.vx*=.998;b.vy*=.999;b.x+=b.vx*step;b.y+=b.vy*step;walls(b)}for(let k=0;k<3;k++)collisions();}particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=150*dt;p.life-=dt});particles=particles.filter(p=>p.life>0);ripples.forEach(p=>{p.r+=100*dt;p.life-=dt});ripples=ripples.filter(p=>p.life>0);floaters.forEach(p=>{p.y-=35*dt;p.life-=dt});floaters=floaters.filter(p=>p.life>0);checkDanger();shake*=.88;}
function walls(b){const floor=H-8;if(b.x-b.r<8){b.x=8+b.r;b.vx=Math.abs(b.vx)*.35}if(b.x+b.r>W-8){b.x=W-8-b.r;b.vx=-Math.abs(b.vx)*.35}if(b.y+b.r>floor){b.y=floor-b.r;if(b.vy>0)b.vy*=-.18;b.vx*=.94}if(b.y-b.r<-100){b.y=-100;b.vy=0}}
function collisions(){for(let i=0;i<bodies.length;i++)for(let j=i+1;j<bodies.length;j++){const a=bodies[i],b=bodies[j];if(a.merge||b.merge)continue;let dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy),min=a.r+b.r;if(d>=min||d===0)continue;if(a.level===b.level&&a.level<LEVELS.length-1&&a.age>.06&&b.age>.06){merge(a,b);return}const nx=dx/d,ny=dy/d,over=min-d,total=a.mass+b.mass;a.x-=nx*over*(b.mass/total);a.y-=ny*over*(b.mass/total);b.x+=nx*over*(a.mass/total);b.y+=ny*over*(a.mass/total);const rv=(b.vx-a.vx)*nx+(b.vy-a.vy)*ny;if(rv<0){const imp=-(1.18)*rv/(1/a.mass+1/b.mass);a.vx-=imp*nx/a.mass;a.vy-=imp*ny/a.mass;b.vx+=imp*nx/b.mass;b.vy+=imp*ny/b.mass;if(Math.abs(rv)>110&&Math.random()<.08)tone("hit")}}}
function merge(a,b){a.merge=b.merge=true;const x=(a.x+b.x)/2,y=(a.y+b.y)/2,l=a.level+1,source=Math.max(a.source,b.source);bodies=bodies.filter(o=>o!==a&&o!==b);const n=createBody(Math.max(LEVELS[l].r+9,Math.min(W-LEVELS[l].r-9,x)),Math.min(H-LEVELS[l].r-9,y),l,source);n.vx=(a.vx+b.vx)*.22;n.vy=Math.min((a.vy+b.vy)*.15,-35);const sameDrop=a.source===dropId||b.source===dropId;if(sameDrop){chain++;clearTimeout(chainTimer);chainTimer=setTimeout(()=>chain=0,1300)}const gain=(l+1)*100*(1+Math.max(0,chain-1)*.5);score+=Math.round(gain);updateScore();burst(n.x,n.y,l,gain);tone(l>=6?"big":"merge",l);if(chain>=2){ui.chain.textContent=`CHAIN ${chain}`;ui.chain.classList.remove("pop");void ui.chain.offsetWidth;ui.chain.classList.add("pop");tone("combo",chain)}shake=Math.min(5,l*.5)}
function burst(x,y,l,gain){const count=8+Math.min(16,l*2);for(let i=0;i<count;i++){const q=Math.random()*Math.PI*2,s=35+Math.random()*100;particles.push({x,y,vx:Math.cos(q)*s,vy:Math.sin(q)*s,life:.45+Math.random()*.25,c:LEVELS[l].c,size:2+Math.random()*3})}ripples.push({x,y,r:LEVELS[l].r*.4,life:.45,c:LEVELS[l].c});floaters.push({x,y:y-10,life:.8,text:`+${gain}`,c:LEVELS[l].c})}
function checkDanger(){const over=bodies.some(b=>b.age>.8&&b.y-b.r<122);if(over){if(!dangerSince){dangerSince=performance.now();tone("warn")}ui.warning.classList.add("on");if(performance.now()-dangerSince>3000)endGame()}else{dangerSince=0;ui.warning.classList.remove("on")}}
function endGame(){gameOver=true;running=false;tone("over");if(score>best){best=score;localStorage.cosmoDropsBest=best}ui.best.textContent=best;$("#finalScore").textContent=score;$("#finalBest").textContent=best;$("#maxLevel").textContent=`${maxLevel+1} · ${LEVELS[maxLevel].n}`;$("#gameoverOverlay").classList.add("visible")}
function updateScore(){ui.score.textContent=score.toLocaleString();if(score>best)ui.best.textContent=score.toLocaleString()}
function draw(){ctx.save();ctx.clearRect(0,0,W,H);ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);ctx.strokeStyle=dangerSince?"#ff4775":"#5ba5c955";ctx.setLineDash([7,7]);ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(8,122);ctx.lineTo(W-8,122);ctx.stroke();ctx.setLineDash([]);if(running&&canDrop){ctx.strokeStyle="#6cecff55";ctx.beginPath();ctx.moveTo(aimX,20);ctx.lineTo(aimX,Math.max(40,bodies.reduce((m,b)=>Math.min(m,b.y-b.r),H-8)));ctx.stroke();drawOrb(ctx,aimX,32,current,.72,true)}for(const r of ripples){ctx.globalAlpha=r.life/.45;ctx.strokeStyle=r.c;ctx.lineWidth=3;ctx.beginPath();ctx.arc(r.x,r.y,r.r,0,7);ctx.stroke()}ctx.globalAlpha=1;for(const b of bodies)drawOrb(ctx,b.x,b.y,b.level,1);for(const p of particles){ctx.globalAlpha=Math.min(1,p.life*3);ctx.fillStyle=p.c;ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,7);ctx.fill()}for(const f of floaters){ctx.globalAlpha=f.life/.8;ctx.fillStyle=f.c;ctx.font="900 15px system-ui";ctx.textAlign="center";ctx.fillText(f.text,f.x,f.y)}ctx.restore();ctx.globalAlpha=1}
function drawOrb(c,x,y,l,scale=1,ghost=false){const L=LEVELS[l],r=L.r*scale;c.save();c.translate(x,y);c.globalAlpha=ghost?.72:1;const g=c.createRadialGradient(-r*.3,-r*.35,r*.05,0,0,r);g.addColorStop(0,"#fff");g.addColorStop(.2,L.c);g.addColorStop(1,"#101338");c.fillStyle=g;c.shadowColor=L.c;c.shadowBlur=ghost?14:7;c.beginPath();c.arc(0,0,r,0,7);c.fill();c.shadowBlur=0;c.strokeStyle="#ffffff88";c.lineWidth=Math.max(1,r*.045);c.stroke();c.globalAlpha*=.45;c.strokeStyle="#fff";c.lineWidth=Math.max(1,r*.04);c.beginPath();c.ellipse(0,0,r*.75,r*.22,-.35,0,7);c.stroke();c.globalAlpha=ghost?.7:1;if(r>16){c.fillStyle="#142042";c.beginPath();c.arc(-r*.25,-r*.05,Math.max(1.5,r*.045),0,7);c.arc(r*.25,-r*.05,Math.max(1.5,r*.045),0,7);c.fill();c.strokeStyle="#142042";c.lineWidth=1.5;c.beginPath();c.arc(0,r*.06,r*.18,.15,Math.PI-.15);c.stroke()}c.restore()}
function drawNext(){nextCtx.clearRect(0,0,72,72);const scale=Math.min(1,25/LEVELS[next].r);drawOrb(nextCtx,36,36,next,scale)}
function loop(t){if(!running)return;const dt=Math.min((t-last)/1000,.025);last=t;if(!paused)update(dt);draw();requestAnimationFrame(loop)}
function pointer(e){const r=canvas.getBoundingClientRect();aimX=Math.max(LEVELS[current].r+9,Math.min(W-LEVELS[current].r-9,e.clientX-r.left))}canvas.addEventListener("pointerdown",e=>{e.preventDefault();pointer(e);canvas.setPointerCapture(e.pointerId)});canvas.addEventListener("pointermove",e=>{if(e.buttons)pointer(e)});canvas.addEventListener("pointerup",e=>{pointer(e);drop()});
function pause(show=true){if(!running||gameOver)return;paused=show;$("#pauseOverlay").classList.toggle("visible",show);if(!show)last=performance.now()}
document.addEventListener("visibilitychange",()=>{if(document.hidden&&running&&!gameOver)pause(true)});$("#play").onclick=start;$("#retry").onclick=start;$("#pause").onclick=()=>pause(true);$("#resume").onclick=()=>pause(false);$("#sound").onclick=()=>{soundOn=!soundOn;localStorage.cosmoDropsSound=soundOn?"on":"off";$("#sound").classList.toggle("muted",!soundOn);initAudio()};
function initAudio(){if(!audio)audio=new (window.AudioContext||window.webkitAudioContext)();if(audio.state==="suspended")audio.resume()}
function tone(type,n=0){if(!soundOn||!audio)return;const now=audio.currentTime,o=audio.createOscillator(),g=audio.createGain();o.connect(g).connect(audio.destination);let f=180,d=.1,w="sine";if(type==="drop"){f=220+n*35;d=.08}if(type==="hit"){f=90;d=.035;w="triangle"}if(type==="merge"){f=330+n*42;d=.18}if(type==="big"){f=180+n*32;d=.35;w="triangle"}if(type==="combo"){f=500+n*60;d=.22}if(type==="warn"){f=130;d=.22;w="sawtooth"}if(type==="over"){f=160;d=.7;w="triangle"}o.type=w;o.frequency.setValueAtTime(f,now);o.frequency.exponentialRampToValueAtTime(type==="over"?60:f*1.7,now+d);g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(type==="warn"?.035:.07,now+.015);g.gain.exponentialRampToValueAtTime(.0001,now+d);o.start();o.stop(now+d+.02)}
resize();drawNext();draw();
